### ISSUE TITLE
目前只能在Ubuntu上运行成功是吗？

### ISSUE THREAD

**Issue by GongChuanZan** [lhw828/timesfm#1]
Windows和Mac都跑不起来吗？
再出一个具体用法的教程吧。

**Comment by lhw828** [comment]
Windows我试过，和99%的人一样，卡在 [https://github.com/google-research/timesfm/issues/1#issue-2285904849](url)
`lingvo`的问题解决不了，即便在conda环境下也是一样。
官方文档已经说了，目前不支持Arm，正在积极解决，所以Mac暂时不用考虑。
Ubuntu下已经跑起来了

**Comment by lhw828** [comment]
如果硬件够好，可以尝试在虚拟机里面试试。
我已测试，可行。

**Comment by lhw828** [comment]
纯CPU模式，10G内存+适当的虚拟内存，可以跑起来。

**Comment by alextooter** [comment]
ubuntu也卡jax和jaxlib的版本问题。

**Comment by lhw828** [comment]
> ubuntu也卡jax和jaxlib的版本问题。

是这两天更新导致的吗？我看这两天有关于这个的合并。

**Comment by 1325075688gw** [comment]
你好，我也是安装lingvo失败，搜了好久的帖子 找到你了。如果需要Ubuntu环境下才能运行，那岂不还要安装虚拟机，那么性能直线下降啊，而且我们肯定还要进行其他业务开发，在虚拟机里面开发业务貌似不妥。我准备寻找其他时序模型了。不过还是感谢你

**Comment by lhw828** [comment]
> 你好，我也是安装lingvo失败，搜了好久的帖子 找到你了。如果需要Ubuntu环境下才能运行，那岂不还要安装虚拟机，那么性能直线下降啊，而且我们肯定还要进行其他业务开发，在虚拟机里面开发业务貌似不妥。我准备寻找其他时序模型了。不过还是感谢你

不太吃硬件，纯cpu跑（我的是e3-1220），哪怕是在虚拟机，只要内存分配多点，30秒左右也能出一次结果。如果有显卡就会更快吧。

**Comment by 1325075688gw** [comment]
可以，不过我已经打算放弃timefm了，因为没有windows版本，我不想在虚拟机上跑



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 上午7:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lhw828/timesfm] 目前只能在Ubuntu上运行成功是吗？ (Issue #1)




  
你好，我也是安装lingvo失败，搜了好久的帖子 找到你了。如果需要Ubuntu环境下才能运行，那岂不还要安装虚拟机，那么性能直线下降啊，而且我们肯定还要进行其他业务开发，在虚拟机里面开发业务貌似不妥。我准备寻找其他时序模型了。不过还是感谢你
  
不太吃硬件，纯cpu跑（我的是e3-1220），哪怕是在虚拟机，只要内存分配多点，30秒左右也能出一次结果。如果有显卡就会更快吧。

**Comment by fangkun1990** [comment]
> ubuntu也卡jax和jaxlib的版本问题。

有找到解决办法么，兄弟~

**Comment by UP61** [comment]
各位大佬，第7步具体如何操作呀，小白一个，PS：我已经注册并获取Access Tokens.
7、获取huggingface Access Tokens 到 https://huggingface.co/settings/tokens 新建一个WRITE属性的Access Tokens 在代码中设置huggingface登录动作 login("从网站复制Tokens到此处") 设置好才能正常获取 google/timesfm-1.0-200m

**Comment by fangkun1990** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我暂时无法亲自回复您的邮件。我会尽快和您取得联系。

**Comment by lhw828** [comment]
> Access Tokens.

将代码中Access Tokens处的***替换成你 自己的Access Tokens.

**Comment by Changretta-y** [comment]
/home/changretta/miniconda3/envs/tfm_env/bin/python /home/changretta/master/timesfm-master/experiments/timesfm1.py 
2024-05-27 12:34:13.982389: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
ERROR:yfinance:Failed to get ticker '^N225' reason: Expecting value: line 1 column 1 (char 0)
[*********************100%%**********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['^N225']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
ERROR:yfinance:Failed to get ticker '^N225' reason: Expecting value: line 1 column 1 (char 0)
[*********************100%%**********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['^N225']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
ERROR:yfinance:Failed to get ticker '^N225' reason: Expecting value: line 1 column 1 (char 0)
[*********************100%%**********************]  1 of 1 completed
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['^N225']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
Traceback (most recent call last):
  File "/home/changretta/master/timesfm-master/experiments/timesfm1.py", line 31, in <module>
    raise ValueError("数据为空，请更改时间区间再试一次或检查网络连接。")
ValueError: 数据为空，请更改时间区间再试一次或检查网络连接。

进程已结束，退出代码为 1
全局代理后报错，这是yfinance接受不到数据麼

**Comment by lhw828** [comment]
> /home/changretta/miniconda3/envs/tfm_env/bin/python /home/changretta/master/timesfm-master/experiments/timesfm1.py 2024-05-27 12:34:13.982389: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory ERROR:yfinance:Failed to get ticker '^N225' reason: Expecting value: line 1 column 1 (char 0) [_**100%%**__] 1 of 1 completed ERROR:yfinance: 1 Failed download: ERROR:yfinance:['^N225']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found') ERROR:yfinance:Failed to get ticker '^N225' reason: Expecting value: line 1 column 1 (char 0) [_**100%%**__] 1 of 1 completed ERROR:yfinance: 1 Failed download: ERROR:yfinance:['^N225']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found') ERROR:yfinance:Failed to get ticker '^N225' reason: Expecting value: line 1 column 1 (char 0) [_**100%%**_*] 1 of 1 completed ERROR:yfinance: 1 Failed download: ERROR:yfinance:['^N225']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found') Traceback (most recent call last): File "/home/changretta/master/timesfm-master/experiments/timesfm1.py", line 31, in raise ValueError("数据为空，请更改时间区间再试一次或检查网络连接。") ValueError: 数据为空，请更改时间区间再试一次或检查网络连接。
> 
> 进程已结束，退出代码为 1 全局代理后报错，这是yfinance接受不到数据麼

提示这个就是无法获取yfinance的数据，应该是魔法有问题。

**Comment by jacklee018** [comment]
> 如果硬件够好，可以尝试在虚拟机里面试试。 我已测试，可行。

请问能够出个虚拟机里的详细教程吗，关于虚拟机的配置啥的。
我在虚拟机ubuntu18.04.6里运行timesfm.py时，同样会遇到“W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory”的问题

**Comment by Changretta-y** [comment]
> > 如果硬件够好，可以尝试在虚拟机里面试试。 我已测试，可行。
> 
> 请问能够出个虚拟机里的详细教程吗，关于虚拟机的配置啥的。 我在虚拟机ubuntu18.04.6里运行timesfm.py时，同样会遇到“W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory”的问题

用cpu版本的不需要配置cuda，虚拟机也不太好用cuda

**Comment by jacklee018** [comment]
> > > 如果硬件够好，可以尝试在虚拟机里面试试。 我已测试，可行。
> > 
> > 
> > 请问能够出个虚拟机里的详细教程吗，关于虚拟机的配置啥的。 我在虚拟机ubuntu18.04.6里运行timesfm.py时，同样会遇到“W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory”的问题
> 
> 用cpu版本的不需要配置cuda，虚拟机也不太好用cuda

请问您在ubuntu虚拟机中运行时，需要修改或者删除源代码中关于cuda或者gpu的内容吗？

**Comment by Changretta-y** [comment]
> > > > 如果硬件够好，可以尝试在虚拟机里面试试。 我已测试，可行。
> > > 
> > > 
> > > 请问能够出个虚拟机里的详细教程吗，关于虚拟机的配置啥的。 我在虚拟机ubuntu18.04.6里运行timesfm.py时，同样会遇到“W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory”的问题
> > 
> > 
> > 用cpu版本的不需要配置cuda，虚拟机也不太好用cuda
> 
> 请问您在ubuntu虚拟机中运行时，需要修改或者删除源代码中关于cuda或者gpu的内容吗？

不需要，我在虚拟机里先安装好梯子，通过yml文件一键安装环境，然后是用了本项目作者得代码。不过我的梯子不知道哪里出了问题，调用不了yfinance的数据和huggingface的模型，我就用tushare的接口，调取股票数据，在huggingface的镜像网站下载模型到本地，成功跑出来了

**Comment by lhw828** [comment]
> > 如果硬件够好，可以尝试在虚拟机里面试试。 我已测试，可行。
> 
> 请问能够出个虚拟机里的详细教程吗，关于虚拟机的配置啥的。 我在虚拟机ubuntu18.04.6里运行timesfm.py时，同样会遇到“W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory”的问题

 我的程序是设定的使用cpu进行预测，出现这个提示可以忽略，不影响出结果。

**Comment by Ai-AlexTomas** [comment]
> > Access Tokens.
> 
> 将代码中Access Tokens处的***替换成你 自己的Access Tokens.

哪个文件中的Access Tokens ，找不到啊

按照步骤做，就差一步了

**Comment by fangkun1990** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我暂时无法亲自回复您的邮件。我会尽快和您取得联系。

**Comment by lhw828** [comment]
> > > Access Tokens.
> > 
> > 
> > 将代码中Access Tokens处的***替换成你 自己的Access Tokens.
> 
> 哪个文件中的Access Tokens ，找不到啊
> 
> 按照步骤做，就差一步了

需要自己去huggingface注册，申请。
