### ISSUE TITLE
用的你的timesfm.py，提示循环导入

### ISSUE THREAD

**Issue by UP61** [lhw828/timesfm#4]
(tfm_env) root@debian:~/timesfm# python timesfm.py
Traceback (most recent call last):
File "/root/timesfm/timesfm.py", line 7, in
from timesfm import TimesFm
File "/root/timesfm/timesfm.py", line 7, in
from timesfm import TimesFm
ImportError: cannot import name 'TimesFm' from partially initialized module 'timesfm' (most likely due to a circular import) (/root/timesfm/timesfm.py)

**Comment by RipperTs** [comment]
+1

**Comment by HuangY0** [comment]
same question

**Comment by HuangY0** [comment]
将你要运行的timesfm.py重命名，不能是timesfm
